language: python

python:
 - "3.6"

install:
 - pip3 install urllib3

script:
 - python src/srconfig.py

after_script:
 - git config user.name "hayden"
 - git config user.email "yangxinhust@hotmail.com"
 - git add -A
 - git commit -m "Dayil Update"
 - git remote add master https://${GH_TOKEN}@github.com:Hsiny/Shadowrocket-Config.git
 - git push --quiet --set-upstream origin master